services:
  # Backend Web Service
  - type: web
    name: trackmint-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Set this manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CORS_ORIGIN
        value: https://trackmint-frontend.onrender.com

  # Frontend Static Site
  - type: static
    name: trackmint-frontend
    plan: free
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://trackmint-backend.onrender.com/api
      - key: VITE_FINNHUB_API_KEY
        sync: false # Set this manually in Render dashboard
      - key: VITE_GEMINI_API_KEY
        sync: false # Set this manually in Render dashboard

# Database (if using Render PostgreSQL - optional)
# databases:
#   - name: trackmint-db
#     plan: free